restaurantes/urls.py
from django.conf.urls import url, include
from rest_framework_mongoengine import routers

from . import views
from . import serializers

router = routers.DefaultRouter()
router.register(r'restaurants', views.restaurantsViewSet, r"restaurants")
router.register(r'restaurantList', views.restaurantListViewSet, r"restaurantList")

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^listar/$', views.listar, name='listar'),
  url(r'^add/$', views.add, name='add'),
  url(r'^search/$', views.search, name='search'),
  url(r'^restaurante/(?P<id>[0-9]{8})/$', views.restaurante, name='restaurante'),
  url(r'^cities/(?P<city>[-\w]+)', views.getCity, name='cities'),
  url(r'^find/image/(?P<address>[-\w]+)', views.getPhoto, name='getPhoto'),
  url(r'^address/(?P<name>[-\w]+)', views.getAddress, name='address'),
  url(r'^image/(?P<file_id>[0-9a-f]{24})/$', views.serve_file, name='gridfs'),
  url(r'^api/', include(router.urls, namespace='api')),
]

sitio_web/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.views.decorators.csrf import csrf_exempt
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib import admin

# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/'

urlpatterns = [
    url(r'^', include('restaurantes.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^tokenauth/obtain-auth-token/$', csrf_exempt(obtain_auth_token)),
]

restaurantes/models.py
from mongoengine import *
from sitio_web.settings import DBNAME
 
connect(DBNAME)

class restaurants(Document):
    name             = StringField(required=True, max_length=80)
    restaurant_id    = StringField()
    cuisine          = StringField()
    borough          = StringField()
    city             = StringField()
    address          = StringField()
    image			 = ImageField(size=(600, 400, True))
    @property
    def gridfile_attr(self):
		return str(self.image.grid_id)

restaurantes/forms.py
# -*- coding: utf-8 -*-
from django import forms

class RestaurantForm(forms.Form):
	
	city = forms.CharField(required=True, label="Ciudad")
	name = forms.CharField(required=True, max_length=80, label="Nombre")
	cuisine = forms.CharField(required=True, label="Cocina")
	borough = forms.CharField(required=True, label="Situación")
	address = forms.CharField(required=True, label="Dirección")
	image = forms.ImageField(label="Imagen", help_text="600x600px")
	image_default = forms.CharField(label="Imagen por Defecto", initial="no")

restaurantes/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, HttpResponse, redirect, Http404
from restaurantes.models import restaurants
from restaurantes.forms import RestaurantForm
import requests
from random import randint
from mongoengine.connection import get_db
from gridfs import GridFS, NoFile
from bson.objectid import ObjectId
from django.contrib.auth.decorators import login_required
import json
#import urllib as ur
import urllib.request as ur # for python 2.7

from django.http import JsonResponse
from io import BytesIO
from PIL import Image

from .serializers import *
from rest_framework_mongoengine import viewsets
from rest_framework.decorators import detail_route
from rest_framework import renderers
from rest_framework import permissions

API_KEY = "%20AIzaSyAlWonn1P-PzadEBz3VWybVtjasLLxSDns"

# Create your views here.

def index(request):
	context = {}   # Aqui van la las variables para la plantilla
	return render(request,'index.html', context)

def listar(request):
	context = {
		"restaurantes": restaurants.objects[:20], # los veinte primeros
		"menu": "listar",
	}
	return render (request, 'listar.html', context)

def serve_file(request, file_id):
	db = get_db()
	fs = GridFS(db)
	try:
		f = fs.get(ObjectId(file_id))
	except NoFile:
		fs = GridFS(db, collection='images') # mongoengine stores images in a separate collection by default
		try:
			f = fs.get(ObjectId(file_id))
		except NoFile:
			raise Http404
		
	response = HttpResponse(f.read(), content_type=f.content_type)
	# add other header data like etags etc. here
	return response

def restaurante(request, id):
	r = restaurants.objects(restaurant_id=str(id)).first()

	context = {
		"restaurante": r,
	}   # Aqui van la las variables para la plantilla
	return render (request, 'restaurante.html', context)

def parseURL(addr):
	addr = addr.encode('utf-8')
	addr = addr.replace("á","a")
	addr = addr.replace("é","e")
	addr = addr.replace("í","i")
	addr = addr.replace("ó","o")
	addr = addr.replace("ú","u")
	addr = addr.replace("ñ","n")
	addr = addr.replace(" ","_")
	return addr

@login_required(login_url='/accounts/login/')
def getPhoto(request, address):
	url = "https://maps.googleapis.com/maps/api/streetview?size=800x600&location="+address+"&key="+API_KEY
	return HttpResponse(ur.urlopen(url).read(), content_type="image/jpeg")

def getCity(request, city):
	url = "https://maps.googleapis.com/maps/api/place/autocomplete/json?input="+city+"&types=(cities)&language=es&key="+API_KEY
	response = ur.urlopen(url)
	data = json.loads(response.read())
	cities=[]
	for c in data["predictions"]:
		cities.append(c["description"])
	return JsonResponse(cities, safe=False)

def getAddress(request, name):
	url = "http://maps.googleapis.com/maps/api/geocode/json?address="+name+"&language=es"
	response = ur.urlopen(url)
	data = json.loads(response.read())
	print(data)
	address=[]
	for c in data["results"]:
		address.append(c["formatted_address"])
	if len(address) == 0:
		address.append("error")
	return JsonResponse(address[0], safe=False)

@login_required(login_url='/accounts/login/')
def add(request):
	if request.method == 'GET':
		formulario = RestaurantForm()
		# GET
		context = {
			'formulario': formulario,
			"menu": "add",
		}   # Aqui van la las variables para la plantilla
		return render(request, 'add.html', context)

	if request.method == 'POST':
		formulario = RestaurantForm(request.POST, request.FILES)
		formulario.is_valid()
		name = formulario.cleaned_data.get('name')
		cuisine = formulario.cleaned_data.get('cuisine')
		borough = formulario.cleaned_data.get('borough')
		city = formulario.cleaned_data.get('city')
		address = formulario.cleaned_data.get('address')
		image_default = formulario.cleaned_data.get('image_default')
		if(image_default == "yes"):
			URL = "https://maps.googleapis.com/maps/api/streetview?size=800x600&location="+address+"&key="+API_KEY
			URL = parseURL(URL)
			image = BytesIO(ur.urlopen(URL).read())
		else:
			image = request.FILES.get('image_file')

		# crear id aleatorio, un numero de 8 cifras y que no se encuentre ya en la base de datos
		restaurant_id = randint(10000000,99999999)
		while(restaurants.objects(restaurant_id=str(restaurant_id)).first() != None):
			restaurant_id = randint(10000000,99999999)

		if(name != "" and cuisine != "" and borough != "" and city != "" and address != ""):
			r = restaurants(name=name, restaurant_id=str(restaurant_id), cuisine=cuisine, borough=borough, city=city, address=address, image=image)
			r.save()
			return redirect('restaurante', id=restaurant_id)
        
	


def search(request):
	context = {
		"restaurantes": restaurants.objects(cuisine__icontains=request.GET.get('cocina')),
	}
	return render (request, 'listar.html', context)


class restaurantsViewSet(viewsets.ModelViewSet):
	lookup_field = 'restaurant_id'
	queryset = restaurants.objects.all()
	serializer_class = restaurantsSerializer
	permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

	@detail_route(renderer_classes=[renderers.StaticHTMLRenderer])
	def highlight(self, request, *args, **kwargs):
		m = self.get_object()
		return Response(m)
	def pre_save(self, obj):
		obj.owner = self.request.user


class restaurantListViewSet(viewsets.ModelViewSet):
	lookup_field = "restaurant_id"
	queryset = restaurants.objects.all()
	serializer_class = restaurantListSerializer
	permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

templates/add.html
{% extends "layout.html" %}
{% load bootstrap4 %}

{% block title %}Añadir restaurante{% endblock %}

{% block content %}
		<h2>Nuevo restaurante</h2>
		<br><br>
		 <div class="row">
			<div class="col-sm-6">
				<form class="form-horizontal form-add" action="{% url 'add' %}" method="POST" enctype="multipart/form-data" id="add-restaurant-form">
					{% csrf_token %}
				
					<div class="form-group has-danger form_city ui-widget">
						<label class="form-control-label" for="id_city">Ciudad</label>
						<input class="form-control" id="id_city" name="city" placeholder="Ciudad" title="" type="text" />
						<small class="text-muted">
							<div class="help-block help-error" id="error_city">Tienes que añadir la ciudad donde se encuentra el restaurante.</div>
						</small>
					</div>
					<div class="form-group has-danger form_name">
						<label class="form-control-label" for="id_name">Nombre</label>
						<input class="form-control" id="id_name" maxlength="80" name="name" placeholder="Nombre del restaurante" title="" type="text" />
						<small class="text-muted">
							<div class="help-block help-error" id="error_name">Tienes que añadir el nombre del restaurante.</div>
						</small>
					</div>
					<div class="form-group has-danger form_name">
						<label class="form-control-label" for="id_address">Dirección</label>
						<div class="row">
							<div class="col-sm-8">
								<input class="form-control" id="id_address" maxlength="80" name="address" placeholder="Dirección del restaurante" title="" type="text" readonly/>
								<small class="text-muted">
									<div class="help-block help-error" id="error_address">Tienes que añadir la dirección del restaurante.</div>
									<div class="help-block" id="address_notfound">No se ha encontrado la dirección</div>
									<div class="help-block"><a id="add-address">Añadir dirección manualmente</a></div>
								</small>
							</div>
							<div class="col-sm-4">
								<button type="button" id="resolve_address" class="btn btn-info">
									Buscar dirección
								</button>
							</div>
						</div>
					</div>
					<div class="form-group has-danger form_cuisine">
						<label class="form-control-label" for="id_cuisine">Cocina</label>
						<input class="form-control" id="id_cuisine" name="cuisine" placeholder="Tipo de cocina" title="" type="text" />
						<small class="text-muted">
							<div class="help-block help-error" id="error_cuisine">Tienes que añadir el tipo de cocina del restaurante.</div>
						</small>
					</div>	
					<div class="form-group has-danger form_borough">
						<label class="form-control-label" for="id_borough">Situación</label>
						<input class="form-control" id="id_borough" name="borough" placeholder="Situación o barrio donde se encuentra el restaurante (por ejemplo: Centro)" title="" type="text" />
						<small class="text-muted">
							<div class="help-block help-error" id="error_borough">Tienes que añadir la situación o barrio del restaurante.</div>
						</small>
					</div>
					<div class="form-group has-danger form_image">
						<label class="form-control-label" for="id_image">Imagen (Pulsa para cambiar la imagen)</label>
						<div class="checkbox" style="margin-bottom: 20px">
							<label><input type="checkbox" value="" checked="checked" id="checkbox-image">Utilizar imagen por defecto</label>
						</div>
						<div class="row bootstrap4-multi-input">
							<div class="col-xs-12">
								<input class="" id="id_image" name="image_file" type="file" disabled/>
								<input class="" id="id_image_default" name="image_default" type="hidden" value="no"/>
							</div>
						</div>
						<small class="text-muted">
							<div class="help-block help-error" id="error_image">Tienes que añadir una imagen del restaurante.</div>
							<div class="help-block">Preferiblemente 600x600px o relación 1:1</div>
						</small>
					</div>
					
					<div class="form-group">
						<button type="submit" class="btn btn-primary">
							<span class="icon icon-star"></span> Insertar
						</button>
					</div>
					
				</form>
			</div>
			<div class="col-sm-6">
				<div id="info-restaurant">
					<img id="img-restaurant"/>
<!-- 				http://gd.geobytes.com/AutoCompleteCity?&q= -->
				</div>
			</div>
		</div>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Restaurantes{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	
	<link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/themes/flick/jquery-ui.css" />
	
	{% load static %}
	
	{% block stylesheet %}{% endblock %}
	
	<link href="{% static 'css/signin.css' %}" rel="stylesheet">
	<link href="{% static 'css/add.css' %}" rel="stylesheet">
  </head>
  <body>
   
    <header>
    {% block header %}
		<nav class="navbar navbar-default" role="navigation">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/">Restaurantes</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li id="listar"><a href="{% url 'listar' %}">Listar</a></li>
						<li id="add"><a href="{% url 'add' %}">Añadir</a></li>
					</ul>
					<div class="col-sm-3 col-md-3">
						<form class="navbar-form" role="search" action="{% url 'search' %}" method="GET">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Buscar por cocina" name="cocina" id="cocina">
							<div class="input-group-btn">
								<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
							</div>
						</div>
						</form>
					</div>
					<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
						<li><a href="#"><span class="glyphicon glyphicon-user"></span> &nbsp; {{ user.get_username }}</a></li>
						<li class="btn-primary"><a href="{% url 'auth_logout' %}" style="color:white"><span class="glyphicon glyphicon-log-out"></span> &nbsp; Salir</a></li>
					{% else %}
						<li class="btn-primary"><a href="{% url 'auth_login' %}" style="color:white"><span class="glyphicon glyphicon-log-in"></span> &nbsp; Entrar</a></li>
					{% endif %}
						
					</ul>
				</div><!-- /.navbar-collapse -->
			</div>
		</nav>
	{% endblock %}
    </header> 
     
    <div class="container">
    {% block content %}{% endblock %}
    </div>
    
    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	
	
	{% block javascript %}{% endblock %}
	
	<script type="text/javascript">
		$(document).ready(function(){  
			$('#{{menu}}').addClass('active');
		});
	</script>
	<script src="{% static 'js/add.js' %}"></script>

  </body>
</html>

templates/listar.html
{% extends "layout.html" %}

{% block title %}Consultar restaurantes{% endblock %}

{% block content %}
	<ul>
		{% for r in restaurantes %}
		<li><a href="{% url 'restaurante' id=r.restaurant_id %}">{{ r.name }}</a> ({{r.cuisine}})</li>
		
		{% endfor %}
    </ul>
{% endblock %}

templates/restaurante.html
{% extends "layout.html" %}

{% load static %}

{% block title %}{{ restaurante.name }}{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-sm-12 col-md-6">
			<h1 class="media-heading">{{ restaurante.name }}</h1>
				<p><b>Cocina:</b> {{ restaurante.cuisine }}</p>
				<p><b>Dirección: </b> {{ restaurante.address }} </p>
				<p><b>Situación:</b> {{ restaurante.borough }}</p>
		</div>
		<div class="col-sm-12 col-md-6">
			<!--<img src="{% static 'images/casajulio.jpg' %}"/>-->
			{% if restaurante.image %}
				<img src="{% url  'gridfs' file_id=restaurante.gridfile_attr %}" />
			{% endif %}
		</div>
	</div>
{% endblock %}